### ISSUE TITLE
Addition of Light Purple to OLEG Brand Kit - #A62258

### ISSUE THREAD

**Issue by a-hebden** [AgePartnership/oleg-brand-kit#7]
Can we add the color: #A62258 to the Oleg Brand Kit?

From PR: https://github.com/AgePartnership/mjolnir-templates/pull/879

https://github.com/AgePartnership/oleg-brand-kit/blob/30dc6058ee90dc981e56f4d3d43f7d746e5f2f36/_config.colour.scss#L25

**Comment by nocturnalmonkey** [comment]
This change is now in PR (https://github.com/AgePartnership/oleg-brand-kit/pull/8) so I'm going to close this off
